FROM python:3.12-slim-bookworm

WORKDIR /app

ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

COPY requirements.txt requirements-consumer.txt ./
RUN pip install -r requirements-consumer.txt

COPY producer ./producer
COPY consumer ./consumer
COPY enrichment ./enrichment
COPY _lib ./_lib

CMD ["python", "-m", "consumer"]
